# Generated by Django 4.2 on 2023-04-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_candidate_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='pasword',
            new_name='password',
        ),
    ]
